default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spree_app_one_dev
  username: root
  password: root

production:
  <<: *default
  database: spree_app_one_prod
  username:
  password:

staging:
  <<: *default
  database: spree_app_one_staging
  username:
  password:
